language: node_js
node_js:
  - "9"
dist: trusty
sudo: requiredbranches:
  only:
  - masterbefore_script:
  - npm install -g @angular/cliscript:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://t-palmer.github.io/angular-metronic-manuel/deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/metronic
  on:
    branch: master

